"""Add percentage and base price

Revision ID: 5e3f45c1e577
Revises: aeaa89b7a840
Create Date: 2026-04-23 18:13:37.141318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3f45c1e577'
down_revision: Union[str, Sequence[str], None] = 'aeaa89b7a840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('percent_threshold', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('base_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'base_price')
    op.drop_column('alerts', 'percent_threshold')
    # ### end Alembic commands ###
